// This file is automatically generated. Do not modify.
export const firebaseConfig = {
  "apiKey": "mock-api-key",
  "authDomain": "mock-project-id.firebaseapp.com",
  "projectId": "mock-project-id",
  "storageBucket": "mock-project-id.appspot.com",
  "messagingSenderId": "mock-sender-id",
  "appId": "mock-app-id",
  "measurementId": "mock-measurement-id"
};
